export const INICIAR_SESION = "INICIAR_SESION";
export const REGISTRARSE = "REGISTRARSE";
export const OBTENER_USUARIO_ACTUAL = "OBTENER_USUARIO_ACTUAL";
export const OBTENER_ADMIN = "OBTENER_ADMIN";
export const RECUPERAR_CONTRASENIA = "RECUPERAR_CONTRASENIA";
export const CERRAR_SESION = "CERRAR_SESION";
