export const FETCH_CLIENTES = "FETCH_CLIENTES";
export const FETCH_CLIENTE = "FETCH_CLIENTE";
export const CREATE_CLIENTE = "CREATE_CLIENTE";
export const UPDATE_CLIENTE = "UPDATE_CLIENTE";
export const DELETE_CLIENTE = "DELETE_CLIENTE";
