export const FETCH_SUCURSALES = "FETCH_SUCURSALES";
export const FETCH_SUCURSAL = "FETCH_SUCURSAL";
export const CREATE_SUCURSAL = "CREATE_SUCURSAL";
export const UPDATE_SUCURSAL = "UPDATE_SUCURSAL";
export const DELETE_SUCURSAL = "DELETE_SUCURSAL";
