export const FETCH_TIPO_DE_TRANSACCIONES = "FETCH_TIPO_DE_TRANSACCIONES";
export const FETCH_TIPO_DE_TRANSACCION = "FETCH_TIPO_DE_TRANSACCION";
export const CREATE_TIPO_DE_TRANSACCION = "CREATE_TIPO_DE_TRANSACCION";
export const UPDATE_TIPO_DE_TRANSACCION = "UPDATE_TIPO_DE_TRANSACCION";
export const DELETE_TIPO_DE_TRANSACCION = "DELETE_TIPO_DE_TRANSACCION";
