export const FETCH_USUARIOS = "FETCH_USUARIOS";
export const FETCH_USUARIO = "FETCH_USUARIO";
export const FETCH_ENTIDAD_BY_USUARIO_ID = "FETCH_ENTIDAD_BY_USUARIO_ID";
export const FETCH_ENTIDADES_BY_PERFIL = "FETCH_ENTIDADES_BY_PERFIL";
export const CREATE_USUARIO = "CREATE_USUARIO";
export const UPDATE_USUARIO = "UPDATE_USUARIO";
export const DELETE_USUARIO = "DELETE_USUARIO";
export const CERRAR_DETALLES = "CERRAR_DETALLES";
